terraform {
  required_version = ">= 1.5.0"

  required_providers {
    trocco = {
      source  = "trocco-io/trocco"
      version = "~> 0.24"
    }
  }
}

provider "trocco" {
  api_key = var.trocco_api_key
  region  = "japan" # "india", "korea"
}

# ─── Snowflake Source Connection ──────────────────────
# snowflake_src_connection_id が設定されている場合: 既存接続を参照（Mode A）
# snowflake_src_connection_id が null の場合: Terraform で新規作成（Mode B）

resource "trocco_connection" "snowflake_source" {
  count = var.snowflake_src_connection_id == null ? 1 : 0

  name            = var.snowflake_src_connection_name
  connection_type = "snowflake"
  description     = "Snowflake ${var.snowflake_src_database}.${var.snowflake_src_schema} (source) - auto-generated by TROCCO Pipeline Builder"

  host        = var.snowflake_src_host
  user_name   = var.snowflake_src_user
  auth_method = var.snowflake_src_auth_method
  password    = var.snowflake_src_auth_method == "user_password" ? var.snowflake_src_password : null
  private_key = var.snowflake_src_auth_method == "key_pair" ? var.snowflake_src_private_key : null
  role        = var.snowflake_src_role
}

# ─── Salesforce Destination Connection ────────────────
# salesforce_dest_connection_id が設定されている場合: 既存接続を参照（Mode A）
# salesforce_dest_connection_id が null の場合: Terraform で新規作成（Mode B）

resource "trocco_connection" "salesforce_dest" {
  count = var.salesforce_dest_connection_id == null ? 1 : 0

  name            = var.salesforce_dest_connection_name
  connection_type = "salesforce"
  description     = "Salesforce ${var.salesforce_dest_object_name} (dest) - auto-generated by TROCCO Pipeline Builder"

  auth_method    = "user_password"
  user_name      = var.salesforce_dest_username
  password       = var.salesforce_dest_password
  security_token = var.salesforce_dest_security_token
  auth_end_point = var.salesforce_dest_auth_end_point
}

locals {
  snowflake_src_connection_id = (
    var.snowflake_src_connection_id != null
    ? var.snowflake_src_connection_id
    : trocco_connection.snowflake_source[0].id
  )
  salesforce_dest_connection_id = (
    var.salesforce_dest_connection_id != null
    ? var.salesforce_dest_connection_id
    : trocco_connection.salesforce_dest[0].id
  )
}

# ─── Job Definition ──────────────────────────────────

resource "trocco_job_definition" "snowflake_to_salesforce" {
  name                     = var.job_name
  description              = var.job_description
  is_runnable_concurrently = false
  retry_limit              = 2

  input_option_type = "snowflake"
  input_option = {
    snowflake_input_option = {
      snowflake_connection_id = local.snowflake_src_connection_id
      database                = var.snowflake_src_database
      schema                  = var.snowflake_src_schema
      query                   = var.snowflake_src_query
      warehouse               = var.snowflake_src_warehouse

      input_option_columns = var.input_columns
    }
  }

  output_option_type = "salesforce"
  output_option = {
    salesforce_output_option = {
      salesforce_connection_id = local.salesforce_dest_connection_id
      object                   = var.salesforce_dest_object_name
      action_type              = var.salesforce_dest_action_type
      api_version              = var.salesforce_dest_api_version
      ignore_nulls             = var.salesforce_dest_ignore_nulls
      throw_if_failed          = var.salesforce_dest_throw_if_failed
      upsert_key               = var.salesforce_dest_action_type == "upsert" ? var.salesforce_dest_upsert_key : null
    }
  }

  filter_columns = var.filter_columns
}
