terraform {
  required_version = ">= 1.5.0"

  required_providers {
    trocco = {
      source  = "trocco-io/trocco"
      version = "~> 0.24"
    }
  }
}

provider "trocco" {
  api_key = var.trocco_api_key
  region  = "japan" # "india", "korea"
}

# ─── S3 Connection ───────────────────────────────────
# s3_connection_id が設定されている場合: 既存接続を参照（Mode A）
# s3_connection_id が null の場合: Terraform で新規作成（Mode B）

resource "trocco_connection" "s3_source" {
  count = var.s3_connection_id == null ? 1 : 0

  name            = var.s3_connection_name
  connection_type = "s3"
  description     = "S3 ${var.s3_bucket} - auto-generated by TROCCO Pipeline Builder"

  # ⚠ aws_assume_role = ... : null の三項演算子は Provider エラーを引き起こす。
  # aws_auth_type に応じて使用する認証ブロックのみ記載すること。
  # 以下は IAM User の例。AssumeRole の場合は aws_iam_user を削除し aws_assume_role を追加。
  aws_auth_type = "iam_user"

  aws_iam_user = {
    access_key_id     = var.s3_aws_access_key_id
    secret_access_key = var.s3_aws_secret_access_key
  }

  # AssumeRole の場合:
  # aws_auth_type = "assume_role"
  # aws_assume_role = {
  #   account_id = var.s3_aws_account_id
  #   role_name  = var.s3_aws_role_name
  # }
}

# ─── Snowflake Connection ────────────────────────────
# snowflake_connection_id が設定されている場合: 既存接続を参照
# snowflake_connection_id が null の場合: Terraform で新規作成

resource "trocco_connection" "snowflake_dest" {
  count = var.snowflake_connection_id == null ? 1 : 0

  name            = var.snowflake_connection_name
  connection_type = "snowflake"
  description     = "Snowflake ${var.snowflake_database}.${var.snowflake_schema} - auto-generated by TROCCO Pipeline Builder"

  host        = var.snowflake_host
  user_name   = var.snowflake_user
  auth_method = var.snowflake_auth_method
  password    = var.snowflake_auth_method == "user_password" ? var.snowflake_password : null
  private_key = var.snowflake_auth_method == "key_pair" ? var.snowflake_private_key : null
  role        = var.snowflake_role
}

locals {
  s3_connection_id = (
    var.s3_connection_id != null
    ? var.s3_connection_id
    : trocco_connection.s3_source[0].id
  )
  snowflake_connection_id = (
    var.snowflake_connection_id != null
    ? var.snowflake_connection_id
    : trocco_connection.snowflake_dest[0].id
  )
}

# ─── Job Definition ──────────────────────────────────
# CSV パーサーの例。他のパーサーの場合は csv_parser を置換する。

resource "trocco_job_definition" "s3_to_snowflake" {
  name                     = var.job_name
  description              = var.job_description
  is_runnable_concurrently = false
  retry_limit              = 2

  input_option_type = "s3"
  input_option = {
    s3_input_option = {
      s3_connection_id = local.s3_connection_id
      bucket           = var.s3_bucket
      region           = var.s3_region
      path_prefix      = var.s3_path_prefix

      # ⚠ decoder は必須。省略すると "Provider produced inconsistent result" エラー
      decoder = {
        match_name = ""
      }

      csv_parser = {
        columns           = var.input_columns
        delimiter         = var.s3_csv_delimiter
        skip_header_lines = var.s3_csv_skip_header_lines
        default_time_zone = var.s3_default_time_zone
      }

      # Excel パーサー使用時は csv_parser の代わりに以下を使用:
      # excel_parser = {
      #   columns           = var.input_columns_excel  # formula_handling 付き
      #   sheet_name        = var.s3_excel_sheet_name
      #   skip_header_lines = var.s3_excel_skip_header_lines
      #   default_time_zone = var.s3_default_time_zone
      # }
    }
  }

  output_option_type = "snowflake"
  output_option = {
    snowflake_output_option = {
      snowflake_connection_id = local.snowflake_connection_id
      warehouse               = var.snowflake_warehouse
      database                = var.snowflake_database
      schema                  = var.snowflake_schema
      table                   = var.snowflake_table
      mode                    = var.snowflake_load_mode
    }
  }

  filter_columns = var.filter_columns
}
