terraform {
  required_version = ">= 1.5.0"

  required_providers {
    trocco = {
      source  = "trocco-io/trocco"
      version = "~> 0.24"
    }
  }
}

provider "trocco" {
  api_key = var.trocco_api_key
  region  = "japan" # "india", "korea"
}

# ─── Salesforce Connection ────────────────────────────
# salesforce_connection_id が設定されている場合: 既存接続を参照（Mode A）
# salesforce_connection_id が null の場合: Terraform で新規作成（Mode B）

resource "trocco_connection" "salesforce_source" {
  count = var.salesforce_connection_id == null ? 1 : 0

  name            = var.salesforce_connection_name
  connection_type = "salesforce"
  description     = "Salesforce ${var.salesforce_object_name} - auto-generated by TROCCO Pipeline Builder"

  auth_method    = "user_password"
  user_name      = var.salesforce_username
  password       = var.salesforce_password
  security_token = var.salesforce_security_token
  auth_end_point = var.salesforce_auth_end_point
}

# ─── Snowflake Connection ────────────────────────────
# snowflake_connection_id が設定されている場合: 既存接続を参照
# snowflake_connection_id が null の場合: Terraform で新規作成

resource "trocco_connection" "snowflake_dest" {
  count = var.snowflake_connection_id == null ? 1 : 0

  name            = var.snowflake_connection_name
  connection_type = "snowflake"
  description     = "Snowflake ${var.snowflake_database}.${var.snowflake_schema} - auto-generated by TROCCO Pipeline Builder"

  host        = var.snowflake_host
  user_name   = var.snowflake_user
  auth_method = var.snowflake_auth_method
  password    = var.snowflake_auth_method == "user_password" ? var.snowflake_password : null
  private_key = var.snowflake_auth_method == "key_pair" ? var.snowflake_private_key : null
  role        = var.snowflake_role
}

locals {
  salesforce_connection_id = (
    var.salesforce_connection_id != null
    ? var.salesforce_connection_id
    : trocco_connection.salesforce_source[0].id
  )
  snowflake_connection_id = (
    var.snowflake_connection_id != null
    ? var.snowflake_connection_id
    : trocco_connection.snowflake_dest[0].id
  )
}

# ─── Job Definition ──────────────────────────────────

resource "trocco_job_definition" "salesforce_to_snowflake" {
  name                     = var.job_name
  description              = var.job_description
  is_runnable_concurrently = false
  retry_limit              = 2

  input_option_type = "salesforce"
  input_option = {
    salesforce_input_option = {
      salesforce_connection_id   = local.salesforce_connection_id
      object                    = var.salesforce_object_name
      object_acquisition_method = var.salesforce_object_acquisition_method

      columns = var.input_columns
    }
  }

  output_option_type = "snowflake"
  output_option = {
    snowflake_output_option = {
      snowflake_connection_id = local.snowflake_connection_id
      warehouse               = var.snowflake_warehouse
      database                = var.snowflake_database
      schema                  = var.snowflake_schema
      table                   = var.snowflake_table
      mode                    = var.snowflake_load_mode
    }
  }

  filter_columns = var.filter_columns
}
