# ─── TROCCO ─────────────────────────────────────────

variable "trocco_api_key" {
  description = "TROCCO API Key"
  type        = string
  sensitive   = true
}

# ─── Salesforce ──────────────────────────────────────
# モードA: salesforce_connection_id を設定 → 既存接続を参照
# モードB: salesforce_connection_id を null → username/password/security_token で新規作成

variable "salesforce_connection_id" {
  description = "Existing TROCCO Salesforce connection ID. If set, skips connection creation."
  type        = number
  default     = null
}

variable "salesforce_connection_name" {
  description = "Connection name in TROCCO (used only when creating new connection)"
  type        = string
  default     = "salesforce-auto"
}

variable "salesforce_username" {
  description = "Salesforce login username (used only when creating new connection)"
  type        = string
  default     = ""
}

variable "salesforce_password" {
  description = "Salesforce login password (used only when creating new connection)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "salesforce_security_token" {
  description = "Salesforce security token (used only when creating new connection)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "salesforce_auth_end_point" {
  description = "Salesforce auth endpoint (default: https://login.salesforce.com/services/Soap/u/). For Sandbox: https://test.salesforce.com/services/Soap/u/"
  type        = string
  default     = "https://login.salesforce.com/services/Soap/u/"
}

variable "salesforce_object_name" {
  description = "Salesforce object name (API name, e.g. Account, Contact, Opportunity)"
  type        = string
}

variable "salesforce_object_acquisition_method" {
  description = "Object acquisition method: all_columns (default) or soql"
  type        = string
  default     = "all_columns"

  validation {
    condition     = contains(["all_columns", "soql"], var.salesforce_object_acquisition_method)
    error_message = "salesforce_object_acquisition_method must be 'all_columns' or 'soql'."
  }
}

# ─── Snowflake ───────────────────────────────────────
# モードA: snowflake_connection_id を設定 → 既存接続を参照
# モードB: snowflake_connection_id を null → host/user/password or private_key で新規作成

variable "snowflake_connection_id" {
  description = "Existing TROCCO Snowflake connection ID. If set, skips connection creation."
  type        = number
  default     = null
}

variable "snowflake_connection_name" {
  description = "Connection name in TROCCO (used only when creating new connection)"
  type        = string
  default     = "snowflake-auto"
}

variable "snowflake_host" {
  description = "Snowflake host (used only when creating new connection)"
  type        = string
  default     = ""
}

variable "snowflake_user" {
  description = "Snowflake username (used only when creating new connection)"
  type        = string
  default     = ""
}

variable "snowflake_auth_method" {
  description = "Snowflake auth method: user_password or key_pair"
  type        = string
  default     = "user_password"

  validation {
    condition     = contains(["user_password", "key_pair"], var.snowflake_auth_method)
    error_message = "snowflake_auth_method must be 'user_password' or 'key_pair'."
  }
}

variable "snowflake_password" {
  description = "Snowflake password (used only when auth_method = user_password)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "snowflake_private_key" {
  description = "Snowflake private key (used only when auth_method = key_pair)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "snowflake_role" {
  description = "Snowflake role (specify the role created for TROCCO)"
  type        = string
}

variable "snowflake_warehouse" {
  description = "Snowflake warehouse name"
  type        = string
}

variable "snowflake_database" {
  description = "Snowflake database name"
  type        = string
}

variable "snowflake_schema" {
  description = "Snowflake schema name"
  type        = string
  default     = "PUBLIC"
}

variable "snowflake_table" {
  description = "Snowflake table name"
  type        = string
}

variable "snowflake_load_mode" {
  description = "Load mode (insert, insert_direct, truncate_insert, replace, merge)"
  type        = string
  default     = "replace"
}

# ─── Job Definition ──────────────────────────────────

variable "job_name" {
  description = "Transfer job name"
  type        = string
}

variable "job_description" {
  description = "Transfer job description"
  type        = string
  default     = "Auto-generated by TROCCO Pipeline Builder"
}

variable "input_columns" {
  description = "Input column definitions"
  type = list(object({
    name   = string
    type   = string
    format = optional(string)
  }))
}

variable "filter_columns" {
  description = "Filter column definitions (source → destination mapping)"
  type = list(object({
    name                = string
    src                 = string
    type                = string
    default             = optional(string, "")
    format              = optional(string)
    json_expand_enabled = optional(bool, false)
  }))
}
