terraform {
  required_version = ">= 1.5.0"

  required_providers {
    trocco = {
      source  = "trocco-io/trocco"
      version = "~> 0.24"
    }
  }
}

provider "trocco" {
  api_key = var.trocco_api_key
  region  = "japan" # "india", "korea"
}

# ─── Google Spreadsheets Connection ──────────────────
# gs_connection_id が設定されている場合: 既存接続を参照（Mode A）
# gs_connection_id が null の場合: Terraform で新規作成（Mode B）

resource "trocco_connection" "google_spreadsheets_source" {
  count = var.gs_connection_id == null ? 1 : 0

  name            = var.gs_connection_name
  connection_type = "google_spreadsheets"
  description     = "Google Spreadsheets - auto-generated by TROCCO Pipeline Builder"

  service_account_json_key = var.gs_service_account_json_key
}

# ─── Snowflake Connection ────────────────────────────
# snowflake_connection_id が設定されている場合: 既存接続を参照
# snowflake_connection_id が null の場合: Terraform で新規作成

resource "trocco_connection" "snowflake_dest" {
  count = var.snowflake_connection_id == null ? 1 : 0

  name            = var.snowflake_connection_name
  connection_type = "snowflake"
  description     = "Snowflake ${var.snowflake_database}.${var.snowflake_schema} - auto-generated by TROCCO Pipeline Builder"

  host        = var.snowflake_host
  user_name   = var.snowflake_user
  auth_method = var.snowflake_auth_method
  password    = var.snowflake_auth_method == "user_password" ? var.snowflake_password : null
  private_key = var.snowflake_auth_method == "key_pair" ? var.snowflake_private_key : null
  role        = var.snowflake_role
}

locals {
  gs_connection_id = (
    var.gs_connection_id != null
    ? var.gs_connection_id
    : trocco_connection.google_spreadsheets_source[0].id
  )
  snowflake_connection_id = (
    var.snowflake_connection_id != null
    ? var.snowflake_connection_id
    : trocco_connection.snowflake_dest[0].id
  )
}

# ─── Job Definition ──────────────────────────────────

resource "trocco_job_definition" "google_spreadsheets_to_snowflake" {
  name                     = var.job_name
  description              = var.job_description
  is_runnable_concurrently = false
  retry_limit              = 2

  input_option_type = "google_spreadsheets"
  input_option = {
    google_spreadsheets_input_option = {
      google_spreadsheets_connection_id = local.gs_connection_id
      spreadsheets_url                  = "https://docs.google.com/spreadsheets/d/${var.gs_spreadsheet_id}/edit"
      worksheet_title                   = var.gs_worksheet_title
      start_row                         = var.gs_start_row
      start_column                      = var.gs_start_column
      default_time_zone                 = var.gs_default_time_zone
      null_string                       = var.gs_null_string

      input_option_columns = var.input_columns
    }
  }

  output_option_type = "snowflake"
  output_option = {
    snowflake_output_option = {
      snowflake_connection_id = local.snowflake_connection_id
      warehouse               = var.snowflake_warehouse
      database                = var.snowflake_database
      schema                  = var.snowflake_schema
      table                   = var.snowflake_table
      mode                    = var.snowflake_load_mode
    }
  }

  filter_columns = var.filter_columns
}
